package modelo.entidad;
// Generated May 7, 2023 2:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="fact"
)
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private String nomProducto;
     private Set detfacts = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(int idProducto, String nomProducto, Set detfacts) {
       this.idProducto = idProducto;
       this.nomProducto = nomProducto;
       this.detfacts = detfacts;
    }
   
     @Id 

    
    @Column(name="idProducto", unique=true, nullable=false)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="nomProducto", length=100)
    public String getNomProducto() {
        return this.nomProducto;
    }
    
    public void setNomProducto(String nomProducto) {
        this.nomProducto = nomProducto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetfacts() {
        return this.detfacts;
    }
    
    public void setDetfacts(Set detfacts) {
        this.detfacts = detfacts;
    }




}


